patterns:
  - на одной оси автомобиля должны быть установлены шины с идентичным протектором.
  - на одной оси должны быть установлены шины с идентичным протектором.
  - оси должны быть установлены шины с идентичным протектором.
  - с идентичным протектором
  - нельзя ставить разные шины
  - нельзя ставить шины с разным протектором
  - одинаковым протектором было
  - с одинаковым идентичным протектором
  - с одинаковым протектором
  - с идентичным протектором
  - должны стоять одинаковые шины
  - На одной оси автомобиля должны быть
  - одинаковый рисунок протектора