patterns:
  - радиус
  - покрышка
  - резина
  - баллон
  - тапок
  - обувка
  - буханка
  - бублик
  - камера
  - переобувка
  - перекидка
  - смена резины
  - липучки
  - всесезонки
  - акб
  - РТТ
  - ФРТТ
  - сосок
  - клапан
  - переходник
  - втулка
  - всесезонка
  - универсалка
  - голая
  - лысая