patterns:
  - акция
  - специальное предложение
  - Диски интересуют
  - Компрессоры интересуют
  - чернитель для шин
  - домкрат
  - компрессор
  - Крепеж
  - записаться на услугу
  - запись на услугу
  - очиститель дисков
  - вентиля
  - колпаки
  - датчики давления
  - вставки
  - центровочные кольца
  - проставки
  - Смазка для электроконтактов
  - провода пусковые
  - зарядное устройство
  - дистиллированная вода
  - средство для тестирования
  - средство для чистки двигателя
  - ключ для снятия фильтра