patterns:
  - минуту, пожалуйста
  - минуту пожалуйста
  - пожалуйста минуту
  - оставайтесь на линии
  - оставайтесь на линию
  - сейчас уточню информацию
  - оставайтесь, пожалуйста, на линии
  - оставайтесь на линии
  - сейчас посмотрим минуту
  - сейчас посмотрим
  - перевести на специалиста
  - Ожидайте, пожалуйста, на линии
  - Ожидайте на линии
  - Ожидайте, пожалуйста
  - Останьте, пожалуйста, на линии
  - , пожалуйста, на линии
