patterns:
  offer:
    - предлагаю оформить заказ
  processing:
    - онлайн или при получении карты или наличкой
    - выберите способ оплаты
  resume:
    - заканчиваем оформление
    - по вашему заказу
    - для получения заказа вы выбрали
    - вы сможете забрать
    - Заказ забронирован
    - Заказ забронированы