patterns:
  offer:
    - предлагаю оформить заказ
    - приступаю к охранению заказа
    - оформляем запись на монтаж
    - Приступай к оформлению заказа
    - предлагаю оформить заказ
    - оформляю заказ
    - Сейчас мы оформим заказ
    - оформлю заказ
    - Оформляем заказ
    - мы оформим заказ
    - забронировать для вас
  processing:
    - онлайн или при получении карты или наличкой
    - выберите способ оплаты
  resume:
    - заканчиваем оформление
    - по вашему заказу
    - проверяем по заказу
    - для получения заказа вы выбрали
    - заказ забронирован
    - заказ забронированы
    - вы забронировали
    - вы записаны на
    - вы заказали
    - вы взяли
    - вы заказаете
    - заберете самовывозом
    - у нас в заказе
    - тогда бронируем
    - заберете самовывозом
    - бронирую для вас
    - у вас будут в заказе
    - итоговая сумма вместе
  order-type:
    tire-service:
      - шиномонтаж
      - шиномонтажом
      - шиномонтажа
      - нашим монтаж
      - феномонтаж
    tire:
      - шина
      - шокардиан
      - шинок
      - шины
      - шин
      - шину
      - шинокардиан
      - шину-навигатор
      - шинал
      - шинелон
      - шинную
      - шинопилизгом
    disk:
      - колесный диск
      - комплект дисков
      - диска
      - вольный диск
      - диск
      - колесо
    wheel:
      - колесо
    lens:
      - линзы
      - линза
    battery:
      - аккумулятор