patterns:
  offer:
    - предлагаю оформить заказ
    - приступаю к охранению заказа
    - оформляем запись на монтаж
    - Приступай к оформлению заказа
    - предлагаю оформить заказ
    - оформляю заказ
    - Сейчас мы оформим заказ
    - оформлю заказ
    - Оформляем заказ
    - мы оформим заказ
    - забронировать для вас
  processing:
    - онлайн или при получении карты или наличкой
    - выберите способ оплаты
  resume:
    - заканчиваем оформление
    - по вашему заказу
    - для получения заказа вы выбрали
    - вы сможете забрать
    - Заказ забронирован
    - Заказ забронированы