speech_patterns:
  interjections: \b(а[а]+|э[э]+|э[м]+|ам[м]+|м[м]+|у[у]+|у[ф]+|фу[ф]+|ф[у]+|ё[ё]+|е[е]+)\b
  parasites:
    - ну
    - вот
    - значит
    - так сказать
    - собственно
    - вообще
    - короче
    - понимаете
    - в общем
    - то есть
    - в принципе
    - блин
    - чё
    - чё-то
    - ага
    - угу
    - ладно
    - окей
    - ясно
    - типа
    - как бы
    - получается
    - собственно говоря
    - вот именно
    - в некотором роде
    - как сказать
    - вроде как
    - вроде бы

  abbreviations_pattern: \b(спс|пжл|плз|нзч|оч|сч|всм|хз|лол|кек|рофл|имхо|збс|пнх|очк|втф)\b

  slang:
    - хай
    - хелло
    - по кайфу
    - норм
    - ок
    - окся
    - офигенно
    - прикольно
    - круто
    - отстой
    - фигня
    - хрень
    - бред
    - зашибись
    - ништяк
    - кайф
    - тащусь
    - ржач
    - прусь
    - агонь
    - жжет
    - пеши
    - рофлишь
    - ауф
    - кринж
    - краш
    - чилить
    - париться
    - залипать

  inappropriate_phrases:
    - ты должен
    - вы должны
    - обязан
    - срочно
    - немедленно
    - не вопрос
    - без проблем
    - не парься
    - забей
    - фиг с ним
    - по ходу
    - как бы не так
    - да ладно
    - не гони
    - не вешай нос
    - держи хвост пистолетом
    - в натуре
    - реально
    - конкретно
    - по факту
    - по-любому
    - жесть
    - c какого города звоните
    - вас беспокоят из