patterns:
  greetings:
    - здравствуйте
    - добрый день
    - добрый вечер
    - добрый вечер
    - доброе утро
    - приветствую вас
    - доброго времени суток
    - приветствую
    - вас беспокоят из
  farewell:
    - всего доброго
    - хорошего дня
    - хорошего вечера
    - до свидания
    - благодарю за обращение
    - приятного дня
    - были рады помочь
    - хорошего настроения
    - был рад помочь
    - была рада помочь
  name-phrases:
    - зовут 
    - меня 
    - это 
    - мое имя 
    - представьтесь 
    - меня зовут