patterns:
  - как я могу к вам обращаться
  - как я могу обращаться
  - чем могу помочь
  - могу я помочь
  - могу предложить вам шины
  - скажите, пожалуйста, какой вопрос у вас
  - сейчас уточню информацию
  - какой вопрос у вас
  - сейчас проверим информацию
  - сейчас проверю информацию
  - переведу вас на другого оператора
  - ожидайте
  - благодарю за обращение
  - благодарю за длительное ожидание
  - благодарю за ожидание
  - оставайтесь, пожалуйста, на линии
  - оставайтесь на линии
  - переведу вас на специалиста
  - ожидайте, пожалуйста, на линии
  - номер телефона, по которому оформляли заказ
