patterns:
  sales:
    - как я могу к вам обращаться
    - как могу к вам обращаться
    - с какого города обращаетесь
    - как я могу обращаться
    - чем могу помочь
    - могу я помочь
    - могу предложить вам шины
    - скажите, пожалуйста, какой вопрос у вас
    - сейчас уточню информацию
    - какой вопрос у вас
    - сейчас проверим информацию
    - сейчас проверю информацию
    - переведу вас на другого оператора
    - ожидайте
    - благодарю за обращение
    - благодарю за длительное ожидание
    - благодарю за ожидание
    - оставайтесь, пожалуйста, на линии
    - оставайтесь на линии
    - переведу вас на специалиста
    - ожидайте, пожалуйста, на линии
    - номер телефона, по которому оформляли заказ
    - благодарю вас за обращение
    - поступит смс с адресом
    - Спасибо за звонок
    - могу вас записать
    - Спасибо за обращение
    - вопросы остались у Вас
    - остались ли у вас вопросы
    - еще какие-либо вопросы остались
    - я могу просто забронировать
    - я просто забронировать
    - для оформления заказа потребуется
    - у вас есть вопросы какие-нибудь
    - уточняю информацию
    - указываете электронную почту
    - выбираете способ оплаты
    - на нашем сайте
    - уточню информацию
    - сейчас озвучу информацию
    - будет выслана анкета
    - как физическое лицо или юридическое лицо
    - проверяю информацию
    - Я вас записала
    - Я вас записал
    - Сейчас посмотрю свободные записи
    - могу к вам прощаться
    - чем я могу вам помочь
    - могу к вам обращаться
    - могу к вам возвращаться
    - я могу помочь?
    - Могу сориентировать по
    - Какой у вас вопрос?
    - как я могу вам обращаться
    - Какой вопрос?
    - на ваш автомобиль
    - Код товара назовите
    - у вас есть номер заказа
    - могу к вам прощать
    - Информацию я передам
    - Информацию передам
    - в каком городе вас интересует
    - могу записать вас
    - Какой у вас запрос
    - приступаю к оформлению заказа
    - как могу я обращаться к вам
    - могу к вам вращаться
    - вы как юридическое лицо
    - Забронируем за вами
    - Вам должно прийти смс
    - Сейчас я проверю, одну минуту
    - у нас нет онлайн-записи
    - Спасибо за ожидание
    - Чем могу вам помочь
    - Потребуется некоторое время
    - Одну минуту уточню
    - Как можно к вам обращаться
    - как я могу вам прощаться
    - как могу обращаться к вам
    - Как могу вам обращаться
    - Уточните, пожалуйста, марку
    - Одну минуту я уточню
    - Вашу запись я перенесла
    - Каким вам обращаться?
    - Вашу запись я перенес
    - как мне к вам обращаться
    - в каком городе на вас посмотреть
    - как мы к вам обращаемся
    - как мне к вам прощаться
    - как я могу попрощаться
    - Каким к вам обращаться
    - Как к вам могу обращаться
    - Какой у вас вопрос
    - вы обращаетесь как
    - Как я могу к вам обратиться
    - кем вы к нам прощаться
    - Проверяю минуту, пожалуйста
    - С какого города вы обращаетесь
    - В каком городе интересует
    - Вы попали на горячую линию
    - Одну минуту.
    - вы можете попасть на другого оператора
    - как мы к вам обращаться
    - как я могу с вами попрощаться
    - я проверю по этому адресу
    - Сейчас уточняю.
    - город у вас какой
    - у вас будет 1 час на оплату
    - Благодарю вас за ожидания
    - сейчас мы ее резервируем
    - как могу к вам прищаться
    - я могу вам помочь
    - Если интересует наличие
    - Как могу к вам обратиться
    - что вас интересует
    - Благодарю вас за ожидание
    - Одну минуту, пожалуйста
    - Можем подобрать альтернативу
    - Каким могу вам прощаться
    - могу вам предложить
    - лучше подобрать две одинаковые модели
    - нету в наличии, к сожалению
    - Заходите на наш сайт
    - можем вас записать на услугу
    - Вентиль это обратный клапан
    - Такой модели, к сожалению, нет
    - Номеров телефона к селению нет
  clients:
    - сколько у вас стоит
    - Хотелось бы уточнить
    - пыталась оформить заказ
    - я ищу
    - молодой человек
    - У меня списались деньги
    - В вашем сервисе
    - Сколько стоимость?
    - Помогите мне, пожалуйста
    - я там менял колеса
    - Хотел бы сегодня подъехать
    - мне нужно колеса заказать
    - у меня вопрос такой
    - заказ сделал на сайте
    - Мы вчера записались
    - Я просто там посмотрел
    - сколько стоит
    - хотел купить
    - Мне нужны шины
    - хотел на шиномонтаж
    - я хотела бы записаться
    - я хотела узнать
    - У меня вопрос по
    - Сориентируйте по цене
    - Хотелось бы перезаписаться
    - Я записалась на
    - Я хотел бы у вас
    - Я хотел заказать
    - Хотел бы посоветоваться
    - у вас заказать
    - Я у вас покупал
    - мне резину надо
    - девушка, подскажите, пожалуйста
    - хотел бы пока отменить
    - Спасибо за консультацию
    - хотел бы отменить
    - я вот сейчас заказал
    - я хотел бы уточнить по наличию
    - у вас есть в наличии
    - на сайте у вас посмотрела
    - на сайте у вас посмотрел
    - Хотел узнать по наличию
    - Подскажите по замене
    - Я записывался
    - А можно записаться на
    - Хотел бы узнать
    - я электронным способом
    - Где можно в ближайшие дни
    - меня интересует наличие
    - меня перенаправьте
    - Хочу отменить запись
    - Я записан
    - я из города
    - Я хотел узнать
    - Я записана на
    - Мы записывались
    - могу я записаться
    - у вас есть хранение резин?
    - я не могу прийти
    - Хотел бы купить
    - Хотел бы колесики
    - Сколько будет стоить
    - приобрел в вашем магазине
    - хотела бы их купить
    - сколько стоит?
    - мне нужна резина
    - У меня такой вопросик
    - У меня такой вопрос
    - сейчас буду смотреть туда
    - Хотелось задать вопрос
    - у вас купить
    - Мне нужно записаться
    - меня интересуют
    - я бы хотел
    - можно записаться?
    - Хотел записаться
    - Хотел бы записаться
    - хочу оформить заказ
    - я на сайте оформляю заказ
