patterns:
  - как я могу к вам обращаться
  - как могу к вам обращаться
  - с какого города обращаетесь
  - как я могу обращаться
  - чем могу помочь
  - могу я помочь
  - могу предложить вам шины
  - скажите, пожалуйста, какой вопрос у вас
  - сейчас уточню информацию
  - какой вопрос у вас
  - сейчас проверим информацию
  - сейчас проверю информацию
  - переведу вас на другого оператора
  - ожидайте
  - благодарю за обращение
  - благодарю за длительное ожидание
  - благодарю за ожидание
  - оставайтесь, пожалуйста, на линии
  - оставайтесь на линии
  - переведу вас на специалиста
  - ожидайте, пожалуйста, на линии
  - номер телефона, по которому оформляли заказ
  - благодарю вас за обращение
  - поступит смс с адресом
  - Спасибо за звонок
  - вопросы остались у Вас
  - остались ли у вас вопросы
  - еще какие-либо вопросы остались
  - я могу просто забронировать
  - я просто забронировать
  - для оформления заказа потребуется
  - у вас есть вопросы какие-нибудь
  - уточняю информацию
  - указываете электронную почту
  - выбираете способ оплаты
