patterns:
  не знаю:
    - не особо
    - не знаю
    - незнаю
    - не знаем
    - я не знаю
    - знать не знаю
    - не зная
    - неизвестно

  не владею:
    - не владею
    - не владеем
    - не владеет
    - не владеют
    - не владения

  нет информации:
    - у меня нет этой информации
    - информации нет
    - нет сведений
    - нет данных
    - инфы нет

  у нас нет:
    - у нас нет
    - нету у нас
    - не имеется
    - отсутствует
    - не в наличии

  не могу:
    - я не могу
    - не могу
    - не можем
    - не смогу
    - не смог
    - не смогла
    - не смогли

  запрещено:
    - запрещено
    - нельзя
    - воспрещается
    - запрещается
    - не разрешается

  вы должны:
    - вы должны
    - вам следует
    - вам надо
    - вам нужно
    - вам необходимо

  я же говорил:
    - я же вам сказал
    - я же говорил
    - я уже сказал
    - повторяю
    - еще раз повторяю

  невозможно:
    - невозможно
    - не представляется возможным
    - нет возможности
    - никак нельзя
    - нереально

  не умею:
    - не умею
    - не умеем
    - не умете
    - не умение
    - не обучен

  не решаю:
    - не решаю
    - не решаем
    - не решает
    - не решение
    - не в моих полномочиях

  не могу помочь:
    - не могу помочь
    - не помогу
    - не помогаю
    - помочь не могу
    - ничем не могу помочь

  не знаю что делать:
    - не знаю что делать
    - не знаю как быть
    - без понятия
    - не представляю
    - в затруднении

  никаких вариантов:
    - никаких вариантов
    - нет вариантов
    - вариантов нет
    - нет решений
    - без вариантов

  не могу сказать:
    - не могу сказать
    - не скажу
    - не вправе сказать
    - не могу сообщить
    - не разглашается

  не моя компетенция:
    - не моя компетенция
    - не в моей компетенции
    - не по моей части
    - не моего уровня
    - не в моих силах

  не могу прокомментировать:
    - не могу прокомментировать
    - без комментариев
    - не комментирую
    - воздержусь от комментариев
    - не дам комментарий

  не могу подтвердить:
    - не могу подтвердить
    - не подтверждаю
    - подтвердить не могу
    - нет подтверждения
    - не подтверждено

  не могу выполнить:
    - не могу выполнить
    - не выполню
    - не исполню
    - не выполняется
    - не исполнимо

  не могу решить:
    - не могу решить
    - не решу
    - решить не могу
    - не решается
    - не разрешимо

  не могу предоставить:
    - не могу предоставить
    - не предоставлю
    - предоставить не могу
    - не предоставляется
    - нет возможности предоставить