patterns:
  swear-words:
    - авотхуй
    - ахуеть
    - безпезды
    - безпизды
    - бля
    - блябуду
    - бляди
    - блядиада
    - блядина
    - блядище
    - блядский
    - блядства
    - блядство
    - блядушник
    - блядь
    - блядью
    - блять
    - взъебну
    - взъебнул
    - взъебнуть
    - впизду
    - впиздячил
    - вхуярил
    - вхуярило
    - вхуярить
    - выблядок
    - выебал
    - выебать
    - выебон
    - гад
    - гадина
    - гандон
    - гандон
    - гандонище
    - гандоша
    - гнида
    - говнюк
    - голоёбица
    - гомодрила
    - гондон
    - далбаёбина
    - дебил
    - дебилойд
    - дерьмо
    - дибил
    - доебался
    - долбаеп
    - долбоёб
    - долбоеб
    - допизды
    - дохуя
    - дура
    - дурак
    - дурачина
    - дурень
    - ебало
    - ебальник
    - ебанёт
    - ебанат
    - ебанатик
    - ебанатство
    - ебанет
    - ебанешь
    - ебанул
    - ебануться
    - ебаныйврот
    - ебанько
    - ебарь
    - ебасос
    - ебать
    - ебашит
    - ебашить
    - ебенить
    - ебистика
    - еблан
    - еблище
    - еблищу
    - ебну
    - ебнул
    - ебнули
    - ебнуть
    - ебнуться
    - ебсти
    - ёб
    - ёбарь
    - ёбля
    - ёбнуть
    - жидоёб
    - заебал
    - заебался
    - заебательский
    - заебать
    - заебаться
    - заебешься
    - заебись
    - заеблось
    - заебнуться
    - заебца
    - залупа
    - залупается
    - залупаюсь
    - залупился
    - злоебучий
    - идиот
    - идиотина
    - изъебнулся
    - козлоёбина
    - лох
    - лохудра
    - лошара
    - лошок
    - манда
    - мандавошка
    - матерщинник
    - мозгоёб
    - мудаг
    - мудак
    - мудила
    - мудиле
    - мудило
    - мудоеб
    - мудя
    - мудям
    - наебал
    - наебщик
    - невъебенно
    - невъебенный
    - нецензурщина
    - объебал
    - однохуйственно
    - опёздл
    - опездл
    - опизденел
    - опизденело
    - отпиздил
    - отпиздить
    - отхуярить
    - отъёбанный
    - отъебали
    - отъебать
    - охуевать
    - охуевший
    - охуеть
    - пёзды
    - падла
    - педик
    - педрила
    - педриле
    - педрилко
    - педрило
    - педрилу
    - пендос
    - переебал
    - пидар
    - пидараз
    - пидарас
    - пидарюка
    - пидор
    - пидораз
    - пидорас
    - пидр
    - пизда
    - пиздабол
    - пиздакрыл
    - пиздализ
    - пиздануть
    - пиздатый
    - пиздеть
    - пиздец
    - пиздецкий
    - пиздил
    - пиздить
    - пиздобратия
    - пиздоватизм
    - пиздоватый
    - пиздовать
    - пиздокрыл
    - пиздос
    - пиздуй
    - пиздун
    - пиздюлина
    - пизды
    - пиндос
    - подиканахуй
    - подъебка
    - поебать
    - поебень
    - поебота
    - поеботина
    - попизде
    - попиздили
    - похуизм
    - похуй
    - похую
    - пошелнахуй
    - пошелпопизде
    - придурок
    - проебал
    - распиздон
    - распиздяй
    - скотоёб
    - скотоебина
    - сосихуй
    - сосихуйский
    - спиздил
    - сракохуй
    - страхоёбище
    - страхуилина
    - сука
    - сучара
    - сучонок
    - сцуко
    - тупарылый
    - тупица
    - тупышка
    - уёбище
    - уебан
    - уебать
    - уебистче
    - урод
    - уродец
    - уродина
    - ушлепок
    - хитровыебанная
    - хитровыебанный
    - хуёво
    - хуевато
    - хуеглот
    - хуегрыз
    - хуем
    - хуеплет
    - хуепутало
    - хуесос
    - хуета
    - хуетень
    - хуи
    - хуило
    - хуита
    - хуй
    - хуйвам
    - хуйвамвсем
    - хуйвот
    - хуйли
    - хуйлище
    - хуйложу
    - хуйморжовый
    - хуйнуть
    - хуйня
    - хуйтам
    - хуйтебе
    - хулинадо
    - хулисмотришь
    - хуя
    - хуяк!
    - хуякс
    - хуярил
    - хуярить
    - хуячить
    - чмо
    - чмошник
    - чмырь
    - БЕСПИЗДАЯ
    - БЛЯ
    - БЛЯДВА
    - БЛЯДИАДА
    - БЛЯДИНА
    - БЛЯДИСТОСТЬ
    - БЛЯДКИ
    - БЛЯДОВАТЬ
    - БЛЯДОГОН
    - БЛЯДОСЛОВНИК
    - БЛЯДСКИЙ
    - БЛЯДСКИЙ
    - БЛЯДСТВО
    - БЛЯДСТВО
    - БЛЯДУН
    - БЛЯДЬ
    - БЛЯХОМУДИЯ
    - ВЗБЛЯД
    - ВЗЪЕБНУТЬ
    - ВЗЪЁБКА
    - ВЗЪЁБЫВАТЬ
    - ВЗЪЕБЩИК
    - ВПИЗДИТЬ
    - ВПИЗДИТЬСЯ
    - ВПИЗДОХАТЬ
    - ВПИЗДОХИВАТЬ
    - ВПИЗДОХИВАТЬСЯ
    - ВПИЗДРОНИВАТЬ
    - ВПИЗДРОНИВАТЬСЯ
    - ВПИЗДЮЛИТЬ
    - ВПИЗДЯЧИЛ
    - ВПИЗДЯЧИТЬ
    - ВПИЗЖИВАТЬ
    - ВПИЗЖИВАТЬСЯ
    - ВХУЙНУТЬ
    - ВХУЙНУТЬСЯ
    - ВХУЯРИВАНИЕ
    - ВХУЯРИТЬ
    - ВЫБЛЯДОВАЛ
    - ВЫБЛЯДОК
    - ВЫЕБАТЬ
    - ВЫЕБОК
    - ВЫЕБОН
    - ВЫЁБЫВАЕТСЯ
    - ВЫПИЗДЕТЬСЯ
    - ВЫПИЗДИТЬ
    - ВЫХУЯРИВАНИЕ
    - ВЪЕБАТЬ
    - ВЪЁБЫВАТЬ
    - ГЛУПИЗДИ
    - ГОВНОЁБ
    - ГОЛОЁБИЦА
    - ГРЕБЛЯДЬ
    - ДЕРЬМОХЕРОПИЗДОКРАТ
    - ДЕРЬМОХЕРОПИЗДОКРАТИЯ
    - ДОЕБАЛСЯ
    - ДОЕБАТЬСЯ
    - ДОЁБЫВАТЬ
    - ДОЛБОЁБ
    - ДОПИЗДЕТЬСЯ
    - ДОХУЙНУТЬ
    - ДОХУЯКАТЬ
    - ДОХУЯКИВАТЬ
    - ДОХУЯРИВАТЬСЯ
    - ДУРОЁБ
    - ДЯДЕЁБ
    - ЕБАЛКА
    - ЕБАЛО
    - ЕБАЛОВО
    - ЕБАЛЬНИК
    - ЕБАНАТИК
    - ЕБАНДЕЙ
    - ЕБАНЁШЬСЯ
    - ЕБАНУЛ
    - ЕБАНУЛСЯ
    - ЕБАНУТЬ
    - ЕБАНУТЬСЯ
    - ЕБАНУТЫЙ
    - ЕБАНЬКО
    - ЕБАРИШКА
    - ЕБАТОРИЙ
    - ЕБАТЬСЯ
    - ЕБАШИТ
    - ЕБЕНЯ
    - ЕБЁТ
    - ЕБИСТИКА
    - ЕБЛАН
    - ЕБЛАНИТЬ
    - ЕБЛИВАЯ
    - ЕБЛЯ
    - ЕБУКЕНТИЙ
    - ЁБАКА
    - ЁБАНЫЙ
    - ЁБАРЬ
    - ЁБКОСТЬ
    - ЁБЛЯ
    - ЁБНУЛ
    - ЁБНУТЬСЯ
    - ЁБНУТЫЙ
    - ЁБС
    - ЖИДОЁБ
    - ЖИДОЁБКА
    - ЖИДОЁБСКИЙ
    - ЗАЕБАЛ
    - ЗАЕБАТЬ
    - ЗАЕБИСЬ
    - ЗАЕБЦОВЫЙ
    - ЗАЕБЕНИТЬ
    - ЗАЁБ
    - ЗАЁБАННЫЙ
    - ЗАЕБАТЬСЯ
    - ЗАПИЗДЕНЕВАТЬ
    - ЗАПИЗДЕТЬ
    - ЗАПИЗДИТЬ
    - ЗАПИЗЖИВАТЬСЯ
    - ЗАХУЯРИВАТЬ
    - ЗАХУЯРИТЬ
    - ЗЛОЕБУЧАЯ
    - ИЗЪЕБНУЛСЯ
    - ИСПИЗДЕЛСЯ
    - ИСПИЗДИТЬ
    - ИСХУЯЧИТЬ
    - КОЗЛОЁБ
    - КОЗЛОЁБИНА
    - КОЗЛОЁБИТЬСЯ
    - КОЗЛОЁБИЩЕ
    - КОНОЁБИТЬСЯ
    - КОСОЁБИТСЯ
    - МНОГОПИЗДНАЯ
    - МОЗГОЁБ
    - МУДОЁБ
    - НАБЛЯДОВАЛ
    - НАЕБАЛОВО
    - НАЕБАТЬ
    - НАЕБАТЬСЯ
    - НАЕБАШИЛСЯ
    - НАЕБЕНИТЬСЯ
    - НАЕБНУЛСЯ
    - НАЕБНУТЬ
    - НАЁБКА
    - НАХУЕВЕРТЕТЬ
    - НАХУЯРИВАТЬ
    - НАХУЯРИТЬСЯ
    - НАПИЗДЕТЬ
    - НАПИЗДИТЬ
    - НАСТОЕБАТЬ
    - НЕВЪЕБЕННЫЙ
    - НЕХУЁВЫЙ
    - НЕХУЙ
    - ОБЕРБЛЯДЬ
    - ОБЪЕБАЛ
    - ОБЪЕБАЛОВО
    - ОБЪЕБАТЕЛЬСТВО
    - ОБЪЕБАТЬ
    - ОБЪЕБАТЬСЯ
    - ОБЪЕБОС
    - ОДИН
    - ХУЙ
    - ОДНОХУЙСТВЕННО
    - ОДИН
    - ХУЙ
    - ОПИЗДЕНЕВАТЬ
    - ОПИЗДИХУИТЕЛЬНЫЙ
    - ОПИЗДОУМЕЛ
    - ОСКОТОЁБИЛСЯ
    - ОСТОЕБАЛ
    - ОСТОПИЗДЕЛО
    - ОСТОПИЗДЕТЬ
    - ОСТОХУЕТЬ
    - ОТПИЗДИТЬ
    - ОТХУЯРИВАТЬ
    - ОТЪЕБАТЬСЯ
    - ОХУЕВАТЬ
    - ПРИХУЕВАТЬ
    - ХУЕТЬ
    - ОХУЕННО
    - ОХУИТЕЛЬНО
    - ОХХУЕТИТЕЛЬНО
    - ОХУЕННЫЙ
    - ОХУИТЕЛЬНЫЙ
    - ОХУЯЧИВАТЬ
    - ОХУЯЧИТЬ
    - ПЕРЕЕБАТЬ
    - ПЕРЕХУЯРИВАТЬ
    - ПЕРЕХУЯРИТЬ
    - ПЁЗДЫ
    - ПИЗДА
    - ПИЗДА
    - ПИЗДАБОЛ
    - ПИЗДАЁБ
    - ПИЗДАКРЫЛ
    - ПИЗДАНУТЬ
    - ПИЗДАНУТЬСЯ
    - ПИЗДАТЫЙ
    - ПИЗДЕЛИТЬСЯ
    - ПИЗДЕЛЯКАЕТ
    - ПИЗДЕТЬ
    - ПИЗДЕЦ
    - ПИЗДЕЦКИЙ
    - ПИЗДЁЖ
    - ПИЗДЁНЫШ
    - ПИЗДИТЬ
    - ПИЗДОБОЛ
    - ПИЗДОБЛОШКА
    - ПИЗДОБРАТ
    - ПИЗДОБРАТИЯ
    - ПИЗДОВАТЬ
    - ПИЗДОВЛАДЕЛЕЦ
    - ПИЗДОДУШИЕ
    - ПИЗДОЁБИЩНОСТЬ
    - ПИЗДОЛЕТ
    - ПИЗДОЛИЗ
    - ПИЗДОМАНИЯ
    - ПИЗДОПЛЯСКА
    - ПИЗДОРВАНЕЦ
    - ПИЗДОСТРАДАЛЕЦ
    - ПИЗДОСТРАДАНИЯ
    - ПИЗДОХУЙ
    - ПИЗДОШИТЬ
    - ПИЗДРИК
    - ПИЗДУЙ
    - ПИЗДУН
    - ПИЗДЮК
    - ПИЗДЮЛИ
    - ПИЗДЮЛИНА
    - ПИЗДЮЛЬКА
    - ПИЗДЮЛЯ
    - ПИЗДЮРИТЬ
    - ПИЗДЮХАТЬ
    - ПИЗДЮШНИК
    - ПОДЗАЕБАТЬ
    - ПОДЗАЕБЕНИТЬ
    - ПОДНАЕБНУТЬ
    - ПОДНАЕБНУТЬСЯ
    - ПОДНАЁБЫВАТЬ
    - ПОДПЁЗДЫВАТЬ
    - ПОДПИЗДЫВАЕТ
    - ПОДЪЕБНУТЬ
    - ПОДЪЁБКА
    - ПОДЪЁБКИ
    - ПОДЪЁБЫВАТЬ
    - ПОЕБАТЬ
    - ПОЕБЕНЬ
    - ПОПИЗДЕТЬ
    - ПОПИЗДИЛИ
    - ПОХУЮ
    - ПОХУЯРИЛИ
    - ПРИЕБАТЬСЯ
    - ПРИПИЗДЕТЬ
    - ПРИПИЗДИТЬ
    - ПРИХУЯРИВАТЬ
    - ПРИХУЯРИТЬ
    - ПРОБЛЯДЬ
    - ПРОЕБАТЬ
    - ПРОЕБАТЬСЯ
    - ПРОЁБ
    - ПРОПИЗДИТЬ
    - РАЗЪЕБАЙ
    - РАЗЪЕБАТЬСЯ
    - РАЗЁБАННЫЙ
    - РАСПИЗДОН
    - РАСПИЗДОШИЛ
    - РАСПИЗДЯЙ
    - РАСПИЗДЯЙСТВО
    - РАСХУЮЖИТЬ
    - РАСХУЯРИВАТЬ
    - СКОТОЁБ
    - СКОТОЁБИНА
    - СОСИХУЙСКИЙ
    - СПИЗДИЛ
    - СТРАХОЁБИЩЕ
    - СУХОПИЗДАЯ
    - СХУЯРИТЬ
    - СЪЕБАТЬСЯ
    - ТРЕПЕЗДОН
    - ТРЕПЕЗДОНИТ
    - ТУЕБЕНЬ
    - ТУПИЗДЕНЬ
    - УЕБАЛСЯ
    - УЕБАТЬ
    - УЁБИЩЕ
    - УЁБИЩЕНСКИ
    - УЁБОК
    - УЁБЫВАТЬ
    - УПИЗДИТЬ
    - ХИТРОВЫЕБАННЫЙ
    - ХУЕВ
    - ХУЕВАТЕНЬКИЙ
    - ХУЕВАТО
    - ХУДОЁБИНА
    - ХУЕБРАТИЯ
    - ХУЕГЛОТ
    - ХУЕГРЫЗ
    - ХУЕДИН
    - ХУЕЛЕС
    - ХУЕМАН
    - ХУЕМЫРЛО
    - ХУЕПЛЁТ
    - ХУЕПУТАЛО
    - ХУЕСОС
    - ХУЕТА
    - ХУЕТЕНЬ
    - ХУЁВИНА
    - ХУЁВНИЧАТЬ
    - ХУЁВО
    - ХУЁВЫЙ
    - ХУИЛА
    - ХУЙЛО
    - ХУЙНУТЬ
    - ХУЙНЯ
    - ХУЙНЯ
    - ХУЯРИТЬ
    - ХУЯЦИЯ
    - ХУЛИ
    - ХУЯ
    - ХУЯК
    - ХУЯЧИТЬ
    - ШАРОЁБИТСЯ
    - ШИРОКОПИЗДАЯ

  char_replacements:
    а: '[а@aа́*]'
    б: '[б6b]'
    в: '[вv]'
    г: '[гg]'
    д: '[дd]'
    е: '[еёe*]'
    з: '[з3z]'
    и: '[иuі*]'
    к: '[кk]'
    о: '[о0oо́*]'
    п: '[пp]'
    р: '[рr]'
    с: '[сc]'
    т: '[тt]'
    у: '[уy*]'
    х: '[хx]'
    ч: '[ч4]'
    я: '[яZ*]'