transcribe:
  model_name: medium
  threads: 2

audio:
  sample_rate: 16000
diarize:
  model_name: speechbrain/spkrec-ecapa-voxceleb
  min_segment_length: 1
  target_segment_length: 1.5

saiga:
  url: http://localhost:11434/v1
  model-name: ilyagusev/saiga_llama3
  api-key: ollama

db:
  dbname: neiro-insight
  user: postgres
  password: 1510261105
  host: localhost
  port: 5432