criteria:
  swear: "true"
  speech_patterns: "true"
  stop_words: "true"
  interjections: "true"
  parasites: "true"
  abbreviations: "true"
  slang: "true"
  inappropriate_phrases: "true"
  order_patterns: "true"
  non_professional_patterns: "true"
  greetings: "true"
  farewell: "true"
  diminutives: "true"
  name: "true"