criteria:
  swear: "false"
  speech_patterns: "false"
  stop_words: "true"
  interjections: "false"
  parasites: "false"
  abbreviations: "false"
  slang: "false"
  inappropriate_phrases: "false"
  order_patterns: "false"
  non_professional_patterns: "false"
  await_request_patterns: "true"
  greetings: "false"
  farewell: "false"
  diminutives: "false"
  name: "false"